name: Release Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
          
      - name: Create icons directory
        run: mkdir -p icons
          
      - name: Install dependencies
        run: npm install
        
      - name: Generate icons
        run: node generate_icons.js
        
      - name: Create release package
        run: |
          zip -r sirtech-whatsapp.zip manifest.json popup.html popup.js background.js content.js icons/
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sirtech-whatsapp.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true 