name: Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Generate icons
        run: npm run generate-icons
        
      - name: Create release package
        run: |
          zip -r sirtech-whatsapp.zip manifest.json popup.html popup.js background.js content.js icons/
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: sirtech-whatsapp.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 